config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get 'd3/show' => 'd3#show'
  get 'd3/index'
  get 'd3/data', :defaults => { :format => 'json' }


  resources :chatrooms, param: :slug
  resources :messages

  root to: 'homepage#homepage'
  get '/homepage' => 'homepage#homepage'


  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/tweets/search' => 'tweets#search'
  post '/tweets/search/:user_id' => 'tweets#save_searches', as: 'update_user_searches'

  resources :tweets

  resources :users

  resources :searches


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  ### Relationships ####
    belongs_to :user

  ### TWITTER API ###
  def self.sync(query, limit, type, name)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "MaqpWY0TO2zBaZ8JHY4W79BKW"
      config.consumer_secret     = "D0R1TpuIMJDjkUoCFY1ShUzDCuagA7iPBDJJtnBG9fsO8cfkaY"
      config.access_token        = "316853982-tPm7s630qJqRoh5p4tLSRP4bX8c3irUlvp4FHvs3"
      config.access_token_secret = "6jRtkivqcQddKyIwvy5Tbh8qdkNIyO0x4NqPBNj9hUSUT"
    end # client

    ### AUTOMATIC SENTIMENT ANALYSIS ###
    results = []
    client.search(query, lang: 'en', :result_type => type, :name => name).take(limit).each do |tweet|
      results.push({
        body: tweet.text,
        # username: tweet.user.screen_name
        score: $analyser.score(tweet.text),
        sentiment: $analyser.sentiment(tweet.text),
        # type: tweet.result_type
      })
    end #search

    results
  end # self sync



end

app/models/user.rb
class User < ApplicationRecord

  has_many :tweets

  has_secure_password
    validates :email, presence: true, uniqueness: true, length: {minimum: 5}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user

  private

  def fetch_user
    #find the current user, their session and if it's present
    @current_user = User.find session[:user_id] if session[:user_id].present?
    #give the sesssion nil if the user is nt present
    session[:user_id] = nil unless @current_user.present?
  end

  def check_if_logged_in
    redirect_to login_path unless @current_user.present?
  end


end

app/controllers/d3_controller.rb
class D3Controller < ApplicationController
  def show
  end

  def index
  end

  def data
   respond_to do |format|
     format.json {
       render :json => [1,2,3,4,5]
     }
   end
 end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def create
  end

  def update
  end

  def index
  end


  def show
  end # end show

  def edit
  end

  def new
  end

  def destroy
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    user = User.find_by email: params[:email]

    if user.present? and user.authenticate params[:password]
      #success!
      session[ :user_id ] = user.id
      redirect_to tweets_path
    else
      #bad credentials
      flash[ :error ] = "Incorrect email address and/or password"
      redirect_to login_path
    end
  end

  def destroy
    session[ :user_id ] = nil
    redirect_to root_path
  end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def create
    @tweet = Tweet.new(search_params)
  end

  def update
  end

  def index
  end

  def show
  end

  # AJAX endpoint for "/tweets/search"
  def search

    # send the original search through the JSON
    puts params
    results = Tweet.sync( params[:query], params[:limit].to_i, params[:type], params[:username] )

    tweets_text = ''

    # save seach function for tweet information
    results.each do |r|
      Tweet.create({
        limit: params[:limit].to_i,
        tweet_type: params[:type],
        query: params[:query],
        body: r[:body],
        sentiment: r[:sentiment].to_s,
        score: r[:score],
      })
      tweets_text += ' ' + r[:body]
    end

    # tokeniser = WordsCounted::Tokeniser.new( tweets_text ).tokenise
    counter = WordsCounted.count( tweets_text )

    ignore_words = ['https']
    word_counts = []

    counter.token_frequency.each do |word|
      if word[0].length > 4 && !ignore_words.include?( word[0] ) && word.count >= 2
        word_counts.push word
      end
    end
    # binding.pry

    render json: { data: results, counter: word_counts }

  end

  # def save_searches
  #   @search = Tweet.find params[:id]
  #
  #   body = params[:query]
  #   limit = param[:limit]
  #   results = Tweet.sync( query, limit.to_i )
  #
  #   render json: { data: results }
  #   search = Tweet.create({
  #       body: tweet.text,
  #       username: twee.user.scree_name
  #   })
  #
  #   # if params[:searches].present?
  #   #   results.each do |t|
  #   #    end
  #   #   end
  #
  # end  # save_searches

  def edit
  end

  def new
    @tweet = Tweet.new
  end

  def destroy
  end


  def private
    params.require(:search).permit(:body, :sentiment_score)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

### Check the user login
before_action :get_user, only: [ :show, :edit, :update ]
# before_action :check_if_admin,  only: [ :index ]

before_action :check_if_logged_in, only: [ :hike_create, :update_hikes ]

  def get_user
     @user = User.find params["id"]
  end

#### Standard CRUD #####

  def create
      @user = User.new(user_params)

        if params[:file].present?
          @user.photo = req['public_id']
        end

        if @user.save
          session[:user_id] = @user.id  # perform login (set session)
          redirect_to user_path(@user.id)   # /users/17
        else
          render :new
        end

  end

  def update

    if params[:file].present?
      @user.photo = req['public_id']
    end

    @user.update user_params
    redirect_to user_path( params["id"] )
  end

  def index
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def destroy
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :business, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/d3_helper.rb
module D3Helper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/d3/show.html.erb
<h1>D3 EXAMPLES</h1>

<div>
  Insert below
</div>

<div class="chart">

</div>

<svg id="graph"></svg>

<svg width="720" height="120">
  <circle cx="40" cy="60" r="10"></circle>
  <circle cx="80" cy="60" r="10"></circle>
  <circle cx="120" cy="60" r="10"></circle>
</svg>

app/views/homepage/homepage.html.erb
<div>
  <h1> TWITTER ANALYSER</h1>
  <h2>HOMEPAGE</h2>
  <h2>The twitttersphere boiled down</h2>
    <div>
      <h3>Want to login?</h3>
      <div class="ui primary basic button">
        <% unless @current_user.present? %>
        <%= link_to 'Login', login_path %>
      </div>

      <h3>Don't have an account? Smash SIGN-UP!</h3>
        <div class="ui secondary basic button">
          <%= link_to 'Signup', new_user_path %>
          <% else %>
        </div>

      <div>
        Welcome, <%= link_to @current_user.name, user_path(@current_user) %> |
        <%= link_to 'Logout', login_path, method: :delete %>
        <% end %> <br>
      </div>

      <h4>OR</h4>
      <h3>Don't really want an acount? </h3>
        <div class="ui negative basic button" >
        <%= link_to 'Go right to searching', tweets_path %>
      </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SENTI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- <script src='../../app/assets/<javascripts></javascripts>/chart.js'> </script>   -->
    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">

    <script src="https://d3js.org/d3.v4.min.js"></script>


    <%= action_cable_meta_tag %>

    <meta charset="utf-8">

  </head>

<body class="<%= controller_name %> <%= action_name %>">

    <nav class="the_nav" class="ui menu">
        <ul>
          <li class="ui black button">
            <%= link_to 'SENTI', homepage_path %>
          </li>
          <li class="ui button">
            <% unless @current_user.present? %>
                <%= link_to 'Login', login_path %>
          </li>
          <li class="ui button">
             <%= link_to 'Signup', new_user_path %>
              <% else %>
            </li>
          <li class="ui button">
            <a <%= link_to @current_user.name, user_path(@current_user)%> ></a>
          </li>
          <li class="ui button">
              <%= link_to 'Logout', login_path, method: :delete%>
              <% end %>
          </li>
          <li class="ui button" id='tweetmain'>
              <%= link_to "Search Tweets", tweets_path %>
          </li>
        </ul>
    </nav>
    <h1>SENTI</h1>


    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_for @search, html: {multipart: true} do |f| %>

  <%= f.label :twitterSearch %>
  <%= f.text_field :twitterSearch %>

  <%= f.submit 'Search twitter', :id => 'newSearch' %>

<% end %>

app/views/searches/create.html.erb
<h1>Searches#create</h1>
<p>Find me in app/views/searches/create.html.erb</p>


<ul>
  <% @tweets.each do |tweet| %>
  <li><%= link_to tweet.text, "https://www.twitter.com/#{tweet.user.screen_name}" %></li>

  <li><% client.update("I'm tweeting with a gem!") %></li>
</ul>

app/views/searches/show.html.erb
<h1>Twitter Senitment Analser</h1>


<input type='text' id='twitterSearch' placeholder='Twitter Search'><br>


<button id='search'>SEARCH</button><br>


<div class='addTweets'></div>


<canvas id="myChart" width="400" height="400"> </canvas>

app/views/session/new.html.erb
<% if flash[ :error ].present? %>
 <p><strong> <%= flash[ :error ] %> </strong></p>
<% end %>

<div class="ui form" id="loginForm">
    <%= form_tag login_path do %>

     <%= label_tag 'Email' %>
     <%= email_field_tag :email, nil %>
     <br>

     <%= label_tag 'Password' %>
     <%= password_field_tag :password, nil %>
     <br>

    <div class="ui teal button">
      <%= submit_tag 'Login'%>
    </div>
    <% end %>
<div>

app/views/tweets/_form.html.erb
<%= form_for @tweet, html: {multipart: true} do |f| %>

  <%= f.label :twitterSearch %>
  <%= f.text_field :twitterSearch %>

  <%= f.submit 'Search twitter', :id => 'newSearch' %>

<% end %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/index.html.erb
<h1>Twitter Senitment Analyser</h1>

<div class= "ui input">
  <input type='text' id='twitterSearch' placeholder='Twitter Search'><br>
</div><br>

<div class= "ui input">
  <input type="text" id="searchNum" placeholder="number">
</div><br>

<form>
  <select class="ui fluid search dropdown" class="searchType" id="searchType">
    <option value="">Select Type Search:</option>
    <option value="recent">Most Recent Tweets</option>
    <option value="popular">Most Popular Tweets</option>
    <option value="mixed">Mixed Tweets</option>
  </select>
</form><br>

<!-- <div class= "ui input">
  <input type="text" placeholder="location">
</div><br> -->

<button class="ui basic button" id='search'>SEARCH</button><br>

<button class="ui basic button" id="saveSearch">SAVE SEARCH</button>

<div class="wordCounter">
</div>

<!-- <div class="d3chart1"></div> -->

<div class="searchHistory">
  <h2>Search history:</h2><br>
  <div>
    <ul class="termsLimit">
    </ul>
  </div>
</div>

<div class="thecharts">
  <canvas id="scoreChart" width="400" height="400"></canvas>
</div>

<div class='tweetFeed'>
  <p class='addTweets'></p>
</div>

<canvas id="sentimentChart" width="400" height="400"> </canvas>


<!--
<canvas id="scatterChart"  width="400" height="4000"></canvas>

<canvas id="wordChart" width="400" height="400"></canvas> -->

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/users/_form.html.erb
<div class="ui form">
  <%= form_for @user, html: {multipart: true} do |f| %>

<div class="two fields">
  <div class="four wide field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
  </div>

  <div class="twelve wide field">
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
  </div>
</div>

  <%= f.label :business %>
  <%= f.text_field :business %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

<div class="ui blue button">
  <%= f.submit %>
</div>

  <% end %>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h4>Edit Account</h4>
<%= render partial: 'form' %>

app/views/users/new.html.erb
<h1 class="ui dividing header">Make an Account</h1>


<div>
  <% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
  <% end %>
  <%= render partial: 'form' %>
</div>

app/views/users/show.html.erb
<h1> Account Details </h1>

<p>Name: <%= @user.name %> </p>
<p>Business: <%= @user.business %> </p>
<p>Email: <%= @user.email %> </p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>